sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: nxcNBzVROmQtRNYoyyqgBOF3Qr0eZr1seyx3aWO0wYqXxEG1XKcMzJumcTrfevToSSZ5gm6RKp4r/jHLFUEAB96WxLwc/FpX1heKcQb/aCVtWix00/TWQ2E2tsrx3ektCbKkvvUTF5IYT6TeTM45N2+P5jjP4NnnbPcwugz4uyjsUXWCUFAQPp1k2Mq3fVsAAWf//PwVCkV03fUWz88Q7aB8tq8Slmy/JGxmoaaNipxm4Rx/SJXGB0/EyPX04LUTRs9c2T7aCOGseW0qzb8NY5cq+Z8TY1XocPrUvd7igevGZn96J6vDHAdtbtBd7kSsry9ciqB9agPznAWvWkPsLGVej6FFcruu7/9WBm/V6saQMLJ3BpGWrvuNYRklKCGdUftWyY/sA375kFbe2s7Y7aSA6Elsvvf0cIzen4RfmW1kE5eyjlcXVO9agwsCGV64F6QL9UThYplxAF9akssA/VtNVtwJbeWka8+hpRw+nezL45j/isQv8rAuytB9stGeZ+7yPJ1LyZBpVMJp9ZiVR/e96ZlQHXzA4WanT9D2+xq2nNGG92+A26b1wz7FbcKpxv4YGjX4xvLBo6UP1kofTZujhf07ouXlO7FzLQZ7nIWIRAs1WMsIE1BlN7tw3Srp741iQFq+yMHJIsbuh710C/saqiwPUIoDcRPGkPrFk/s=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Girl-Scout-Pioneers-Or-Winning-the-First-B-C_5263
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy